on: [push]
  
jobs:
  polaris_code_scanning_run_steps:
    runs-on: ubuntu-latest
    container:
      image: docker.io/mjones6951/polaris:latest
      credentials:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    env:
      POLARIS_SERVER_URL:  ${{ secrets.POLARIS_URL }}
      POLARIS_ACCESS_TOKEN:  ${{ secrets.POLARIS_TOKEN }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
  
      - name: Polaris analysis
        run:
          polaris -c polaris-incremental.yml analyze -w
